services:
  - type: web
    name: leave-management
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aquasens.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: leave-management.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: aquasens.settings
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: leave-management-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: leave-management-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: leave-management-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: leave-management-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: leave-management-db
          property: port
