# Generated by Django 5.2 on 2025-04-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin')], default='staff', max_length=20)),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='MonitoringData',
        ),
    ]
