# Generated by Django 5.2 on 2025-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_leavebalance_leaverequest_leavetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='default_days',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='days_allowed',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_document',
            field=models.BooleanField(default=False),
        ),
    ]
