# Generated by Django 5.2 on 2025-04-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproval', '0002_approval_leaverequest_delete_sensor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='leave_request',
        ),
    ]
